# -*- coding: utf-8 -*-
"""Customer_Segmentation_KMeans.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nX6MatwSUGl7TZ3r8ymB6VwRQ3Umx2uA
"""

# 1. Install Dependencies (Run this first!)
!pip install kagglehub

# 2. Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
import kagglehub
from kagglehub import KaggleDatasetAdapter

# 3. Load Data using KaggleHub
print("Downloading and loading dataset...")

# Set the path to the file you'd like to load
# Note: The file name in this dataset is 'Mall_Customers.csv'
file_path = "Mall_Customers.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "vjchoudhary7/customer-segmentation-tutorial-in-python",
  file_path
)

print("--- Data Loaded Successfully ---")
print("First 5 records:")
print(df.head())

# 4. Preprocessing
# We only need 'Annual Income (k$)' and 'Spending Score (1-100)' for clustering
# These are usually columns 3 and 4 (index 3 and 4)
X = df.iloc[:, [3, 4]].values

# 5. Finding the Optimal Number of Clusters (The Elbow Method)
wcss = [] # Within-Cluster Sum of Square

for i in range(1, 11):
    kmeans = KMeans(n_clusters=i, init='k-means++', random_state=42)
    kmeans.fit(X)
    wcss.append(kmeans.inertia_)

# Plotting the Elbow Graph
plt.figure(figsize=(10, 5))
plt.plot(range(1, 11), wcss, marker='o')
plt.title('The Elbow Method')
plt.xlabel('Number of clusters')
plt.ylabel('WCSS')
plt.show()

# NOTE: The Elbow usually appears at K=5 for this dataset.

# 6. Training the K-Means Model (with K=5)
kmeans = KMeans(n_clusters=5, init='k-means++', random_state=42)
y_kmeans = kmeans.fit_predict(X)

# 7. Visualizing the Clusters
plt.figure(figsize=(12, 7))

# Plotting each cluster
plt.scatter(X[y_kmeans == 0, 0], X[y_kmeans == 0, 1], s=100, c='red', label='Careful (High Income, Low Spend)')
plt.scatter(X[y_kmeans == 1, 0], X[y_kmeans == 1, 1], s=100, c='blue', label='Standard (Average Income, Average Spend)')
plt.scatter(X[y_kmeans == 2, 0], X[y_kmeans == 2, 1], s=100, c='green', label='Target (High Income, High Spend)')
plt.scatter(X[y_kmeans == 3, 0], X[y_kmeans == 3, 1], s=100, c='cyan', label='Careless (Low Income, High Spend)')
plt.scatter(X[y_kmeans == 4, 0], X[y_kmeans == 4, 1], s=100, c='magenta', label='Sensible (Low Income, Low Spend)')

# Plotting the Centroids
plt.scatter(kmeans.cluster_centers_[:, 0], kmeans.cluster_centers_[:, 1], s=300, c='yellow', label='Centroids', marker='*')

plt.title('Customer Segments')
plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending Score (1-100)')
plt.legend()
plt.show()